### ISSUE TITLE
Autoclosing (FIXED)

### ISSUE THREAD

**Issue by ishmael205** [Radfordhound/SLW-Mod-Loader#1]
EDIT: I found the issue!
I followed the instructions exactly, but every time I open cpkmakec, it opens a command prompt and immediately closes after a split second. Please fix this!!

**Comment by Radfordhound** [comment]
Since you say you've fixed the issue, I assume you already know this, but why are you opening cpkmakec? The mod loader's executable is SLWModLoader.exe :P

**Comment by ishmael205** [comment]
Didn't release it was in the bin folder. Lol.

**Comment by Radfordhound** [comment]
Oh, ok. xD Thanks for letting me know what happened! :)
