### ISSUE TITLE
WHY RADFORD?!??!

### ISSUE THREAD

**Issue by Advkid** [Radfordhound/SLW-Mod-Loader#15]
ok my problem is that when i try to patch my sonic lost world to be able to be modded, it crashes!
if i skip that then try to save, it crashes!!! 
and i downloaded slw just for using your mod launcher. :(

**Comment by GoldtexTwitch** [comment]
Woah woah woah, chill down.

What version of SLW are you using? Is it from Steam or is it pirated/cracked?

**Comment by Radfordhound** [comment]
Hey, man! Sorry to hear that! Could you possibly give us a little more information?

As goldtex asked, is your SLW pirated/cracked? Or did you buy it from Steam? SLW mod loader only supports the official Steam version for legal reasons, so if it's crashing and you're not using the Steam version, that's probably why.

**Comment by Advkid** [comment]
Ok sorry for not being chill
yes it is cracked BUT(plz dont hate me for that)
ive used your mod loader on a cracked version on my old laptop
i just dont know what could be the problem.
maybe you have updated it so i doesnt support cracked.
i owned the game before but i lost my steam account ( sad)
but thanks for taking this time to reply.

**Comment by GoldtexTwitch** [comment]
If it's cracked, then it won't work. Purchase Sonic Lost World off Steam.

**Comment by Advkid** [comment]
Okie sorry for my trouble

**Comment by GoldtexTwitch** [comment]
It's okay, we're just letting you know that SLW Mod Loader only works with a Steam copy of the game. I wish you good luck on recovering your Steam account.

**Comment by Radfordhound** [comment]
I'm closing this issue for now since the problem seems to be resolved. :) If you'd like to discuss the issue further, feel free to re-open it!
