### ISSUE TITLE
hi can you add this feture to da senic lust hiz warld mLD LOADFGR

### ISSUE THREAD

**Issue by ThomasandSonic1991** [Radfordhound/SLW-Mod-Loader#16]
HAAI RBSAB FURDHERND CNSNAN Y9OUFD ADD MAOR OPTAINZ PLAZ TANSKH

(translation: can you add more options please -Slash)

**Comment by GoldtexTwitch** [comment]
We will add more options during the release. Also I've added on a translation for those who can't understand the original post. Closing.
