### ISSUE TITLE
This Doesen't Work

### ISSUE THREAD

**Issue by jnaskdns** [Radfordhound/SLW-Mod-Loader#20]
i tried using this but the mods won't load.

**Comment by thesupersonic16** [comment]
What version of SLWModLoader are you using?

**Comment by jnaskdns** [comment]
thesupersonic16 i'm using version 5.3

**Comment by thesupersonic16** [comment]
Sorry for not answering, What happens when you try to load mods? Like the game not load?, error Message? or the game act as if you didn't have the loader installed?
