### ISSUE TITLE
Compatibility with cracked versions...

### ISSUE THREAD

**Issue by HunterPvP013** [Radfordhound/SLW-Mod-Loader#22]
Being too cheap to buy a full, legit copy of the game, yet I wanted to play SLW, I ended up getting a cracked version of the game. And I was fairly disappointed when I tried launching the game with the mod loader - especially, because I'm a hardcore Sonic.EXE fan, because of how EPIC that thing could be -... eventually I landed on the game's Steam Store website. So yeah, I guess you know where I'm going with this...

**Comment by thesupersonic16** [comment]
I'm sorry, But pirated copies of SLW is not supported, And may never be.
Also this has already been reported and answered, For More info Please read: https://github.com/Radfordhound/SLW-Mod-Loader/issues/7#issuecomment-168464427

**Comment by blueskythlikesclouds** [comment]
We do not support piracy. Closing.

**Comment by HunterPvP013** [comment]
Okay understood and thank you for the reply and I’m really sorry for repost... but I didn’t saw that comment
