### ISSUE TITLE
quando eu entro no hedgemodmanager e coloco o mod entra em sônico e depois sai e quando entra sem ele sai fica sem o mod

### ISSUE THREAD

**Issue by DARKTHEHEDGEHOG** [Radfordhound/SLW-Mod-Loader#23]

**Comment by thesupersonic16** [comment]
Issues for HedgeModManager doesn't belong in SLW-Mod-Loader's Issue tracker, please go to HedgeModManager's Issue tracker and reply in the appropriate issue with what's wrong. 

Tip: "Please help me" is very unhelpful.

Also you need to stop spamming aswell it's causing the opposite effect. Closing...
