### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by JuliOooO36** [Radfordhound/SLW-Mod-Loader#3]
Can you help me it's not working i created the folder, uploaded the mod and also tried using version 4.4 but nothing changes

**Comment by Radfordhound** [comment]
Thanks for reporting the issue. :) Are you using the mod loader with a legally-purchased version of the game? If so, where did you install the game/mod loader at?

**Comment by JuliOooO36** [comment]
Hi, yes, I bought the game on steam. I installed the game on an external hard drive and I have put the mod loader in that folder. After opening the loader and checking the "super sonic" mod or any other that I got the game opens but sonic looks the same its not changing.

ps. I also tried with other versions of the mod but it didn't work

thank you, I hope you can help me!

**Comment by Radfordhound** [comment]
Thanks for the info! Could you possibly attach a copy of your slw.exe, so I can verify that it's been properly patched by the mod loader? This seems to be a common glitch people are having, so being able to look into it a little would be awesome. :)

**Comment by JuliOooO36** [comment]
Sure, do you know what I could do to fix, how to patch it again? thank you!


Slw.exe: http://www.mediafire.com/download/4avndtnmao0ombr/slw.zip

2015-11-24 22:26 GMT-05:00 Radfordhound <notifications@github.com>:

**Comment by Radfordhound** [comment]
Alright, from what I'm seeing it appears your exe file is un-patched. When you open the mod loader, do you get a prompt to patch it? Something like this?

![CPKREDIR prompt](http://i.imgur.com/sTPv9nQ.png)

**Comment by JuliOooO36** [comment]
No, I don't get that. I only get the window to select the mod and press play :/

**Comment by Radfordhound** [comment]
Huh... that's odd. ._. Well, thanks for letting me know!

[Here](https://www.dropbox.com/s/od1jkjgh40vp5pf/slw.exe?dl=0) is a patched copy of the executable. Just replace yours with this one, and you should be good to go. ;)

Please let me know once you've relieved it, however, as I wish to remove it as soon as possible for copyright reasons.

**Comment by JuliOooO36** [comment]
Thanks, I downloaded and replaced it in the folder- but it still doesn't
work ;(

2015-11-24 23:02 GMT-05:00 Radfordhound <notifications@github.com>:

**Comment by Radfordhound** [comment]
Wow.. that's really weird. O.o Is your cpkredir.dll contained within the same folder as your slw.exe?

**Comment by JuliOooO36** [comment]
Yes it is :/

**Comment by Radfordhound** [comment]
How is the mod you're trying to load set up? For example, does your mod contain a mod.ini file?

**Comment by JuliOooO36** [comment]
Hi, I have it like this, the folder name example: "Classic Sonic", inside that folder there's a folder called "disk" and one file called mod.ini. 

Inside "disk" > folder "sonic2013_patch_0" and inside >Sonic.pac, Sonic.pac00, Supersonic.pac, Supersonic.pac.00

thank you!

**Comment by Radfordhound** [comment]
Yeah, that's correct. :| What's your ModsDB.ini file look like inside of your "mods" folder?

**Comment by JuliOooO36** [comment]
[image: Imagen integrada 2]


Hi, it looks like that

2015-11-26 18:50 GMT-05:00 Radfordhound <notifications@github.com>:

**Comment by Radfordhound** [comment]
Apologies, but I can't see an image from here, only the text "[image: Imagen integrada 2]." :(
Could you just copy and paste the text inside of your ModsDB.ini file? That's all I need to see. ;)

**Comment by JuliOooO36** [comment]
Hi, I fixed it!

the problem was that my "mods" folders were created inside another folder called "mods" and even when the moadloader detected, it wasn't working. So what I did was erase the mods folder and create it again to make it be Sonicthenaneofgame/mods instead of Sonicthenameofgame/mods/mods/

I hope you can understand what I said, sorry for the English and thanks for helping me these days!

**Comment by Radfordhound** [comment]
No problem! Glad to hear the problem's been resolved! :D

Lemme' know if you have any more issues!
