### ISSUE TITLE
Auto-Saving Mod List

### ISSUE THREAD

**Issue by GoldtexTwitch** [Radfordhound/SLW-Mod-Loader#4]
The mod list currently resets every time you start the mod loader. This makes it hard if you want to switch up one of your mods (like maybe change a level mod or character mod) but you have to scroll down a long list of mods to find the one you want and have picked previously every time you start up the loader. Auto-saving the mod list will make that a ton easier. Maybe you could have the loader read the ModsDB.ini to see the active mods and automatically check them?

**Comment by Radfordhound** [comment]
Yeah... this is a feature I currently haven't implemented that I've been planning on doing since day one. Thanks for reminding me! :) I'll get right to it.

**Comment by Radfordhound** [comment]
Alright, it should be implemented now. ;) Please try updating the mod loader by opening the version you currently have (I assume 4.4) and clicking "Yes" when prompted to update.
