### ISSUE TITLE
Sonic Lost World EXE breaking

### ISSUE THREAD

**Issue by LuigiSpeed7** [Radfordhound/SLW-Mod-Loader#5]
Hey, so i believe when the "Auto-Updater" thing was released, my game started to bug out a little. I tried using it, and once it patched my SLW.exe.. the mods stopped working. Thankfully i fixed this with the help of smashpersona. but.. when v4.3 came along, it broke even more. And by that i mean SLW crashes when i open it. And the auto updater doesn't work either. Every time i try to update, it finishes.. but when i open the mod loader again, it says i need to update again! So the update did nothing. Recently i was able to fix it slightly by using the backup exe. But i still can't use mods. Infact with the backup, i can't even open the game from the directory. Only from Steam. Can you please help? I see all these mods and i can't use them. And if you need, i will upload images as soon as i can.

**Comment by LuigiSpeed7** [comment]
Oh wait, Sorry. I just tried installing the new Mod loader, and its fixed. xD
I will let you know if i find anymore problems. Because i like to find a lot. :/

**Comment by Radfordhound** [comment]
Sorry for the trouble. :( Glad to hear it's working now, though! :)

Just for future reference, however, the mod loader's supposed to re-open itself after completing the update process, so maybe that's what the problem was? O.o

Regardless, please let me know if you have any issues in the future!

**Comment by LuigiSpeed7** [comment]
It did re-open itself, but it still told me to install the new one.

**Comment by Radfordhound** [comment]
Yeah.. that's a glitch I get myself, occasionally. :| I've been trying to fix that... but don't quite know why it happens. .__. My guess would be maybe something isn't being downloaded 100% successfully?

Regardless, if it re-opens itself after "updating" and is still on the old version, just try clicking "Yes" to update it again. It usually seems to work after the second try or so. :P
